# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wangyang/workspace/develop/opensource/body_detect

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wangyang/workspace/develop/opensource/body_detect

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangyang/workspace/develop/opensource/body_detect/CMakeFiles /home/wangyang/workspace/develop/opensource/body_detect//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wangyang/workspace/develop/opensource/body_detect/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bodydetect

# Build rule for target.
bodydetect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bodydetect
.PHONY : bodydetect

# fast build rule for target.
bodydetect/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bodydetect.dir/build.make CMakeFiles/bodydetect.dir/build
.PHONY : bodydetect/fast

#=============================================================================
# Target rules for targets named det_body_ssd

# Build rule for target.
det_body_ssd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 det_body_ssd
.PHONY : det_body_ssd

# fast build rule for target.
det_body_ssd/fast:
	$(MAKE) $(MAKESILENT) -f det_body_ssd/api/CMakeFiles/det_body_ssd.dir/build.make det_body_ssd/api/CMakeFiles/det_body_ssd.dir/build
.PHONY : det_body_ssd/fast

#=============================================================================
# Target rules for targets named facethink_caffe_GPU

# Build rule for target.
facethink_caffe_GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 facethink_caffe_GPU
.PHONY : facethink_caffe_GPU

# fast build rule for target.
facethink_caffe_GPU/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/caffe/CMakeFiles/facethink_caffe_GPU.dir/build.make caffe_inference_base/caffe/CMakeFiles/facethink_caffe_GPU.dir/build
.PHONY : facethink_caffe_GPU/fast

#=============================================================================
# Target rules for targets named ict_ssd_test_GPU

# Build rule for target.
ict_ssd_test_GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ict_ssd_test_GPU
.PHONY : ict_ssd_test_GPU

# fast build rule for target.
ict_ssd_test_GPU/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/test/CMakeFiles/ict_ssd_test_GPU.dir/build.make caffe_inference_base/test/CMakeFiles/ict_ssd_test_GPU.dir/build
.PHONY : ict_ssd_test_GPU/fast

#=============================================================================
# Target rules for targets named landmark_net_test_GPU

# Build rule for target.
landmark_net_test_GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 landmark_net_test_GPU
.PHONY : landmark_net_test_GPU

# fast build rule for target.
landmark_net_test_GPU/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/test/CMakeFiles/landmark_net_test_GPU.dir/build.make caffe_inference_base/test/CMakeFiles/landmark_net_test_GPU.dir/build
.PHONY : landmark_net_test_GPU/fast

#=============================================================================
# Target rules for targets named face_det_test_GPU

# Build rule for target.
face_det_test_GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 face_det_test_GPU
.PHONY : face_det_test_GPU

# fast build rule for target.
face_det_test_GPU/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/test/CMakeFiles/face_det_test_GPU.dir/build.make caffe_inference_base/test/CMakeFiles/face_det_test_GPU.dir/build
.PHONY : face_det_test_GPU/fast

#=============================================================================
# Target rules for targets named face_angle_test_GPU

# Build rule for target.
face_angle_test_GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 face_angle_test_GPU
.PHONY : face_angle_test_GPU

# fast build rule for target.
face_angle_test_GPU/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/test/CMakeFiles/face_angle_test_GPU.dir/build.make caffe_inference_base/test/CMakeFiles/face_angle_test_GPU.dir/build
.PHONY : face_angle_test_GPU/fast

#=============================================================================
# Target rules for targets named ssd_shuffle_test_GPU

# Build rule for target.
ssd_shuffle_test_GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ssd_shuffle_test_GPU
.PHONY : ssd_shuffle_test_GPU

# fast build rule for target.
ssd_shuffle_test_GPU/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/test/CMakeFiles/ssd_shuffle_test_GPU.dir/build.make caffe_inference_base/test/CMakeFiles/ssd_shuffle_test_GPU.dir/build
.PHONY : ssd_shuffle_test_GPU/fast

#=============================================================================
# Target rules for targets named ssd_test_GPU

# Build rule for target.
ssd_test_GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ssd_test_GPU
.PHONY : ssd_test_GPU

# fast build rule for target.
ssd_test_GPU/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/test/CMakeFiles/ssd_test_GPU.dir/build.make caffe_inference_base/test/CMakeFiles/ssd_test_GPU.dir/build
.PHONY : ssd_test_GPU/fast

#=============================================================================
# Target rules for targets named faster_rcnn_net_test_GPU

# Build rule for target.
faster_rcnn_net_test_GPU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 faster_rcnn_net_test_GPU
.PHONY : faster_rcnn_net_test_GPU

# fast build rule for target.
faster_rcnn_net_test_GPU/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/test/CMakeFiles/faster_rcnn_net_test_GPU.dir/build.make caffe_inference_base/test/CMakeFiles/faster_rcnn_net_test_GPU.dir/build
.PHONY : faster_rcnn_net_test_GPU/fast

#=============================================================================
# Target rules for targets named blob_test

# Build rule for target.
blob_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blob_test
.PHONY : blob_test

# fast build rule for target.
blob_test/fast:
	$(MAKE) $(MAKESILENT) -f caffe_inference_base/test/CMakeFiles/blob_test.dir/build.make caffe_inference_base/test/CMakeFiles/blob_test.dir/build
.PHONY : blob_test/fast

body_detect.o: body_detect.cpp.o

.PHONY : body_detect.o

# target to build an object file
body_detect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bodydetect.dir/build.make CMakeFiles/bodydetect.dir/body_detect.cpp.o
.PHONY : body_detect.cpp.o

body_detect.i: body_detect.cpp.i

.PHONY : body_detect.i

# target to preprocess a source file
body_detect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bodydetect.dir/build.make CMakeFiles/bodydetect.dir/body_detect.cpp.i
.PHONY : body_detect.cpp.i

body_detect.s: body_detect.cpp.s

.PHONY : body_detect.s

# target to generate assembly for a file
body_detect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bodydetect.dir/build.make CMakeFiles/bodydetect.dir/body_detect.cpp.s
.PHONY : body_detect.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... blob_test"
	@echo "... bodydetect"
	@echo "... det_body_ssd"
	@echo "... face_angle_test_GPU"
	@echo "... face_det_test_GPU"
	@echo "... facethink_caffe_GPU"
	@echo "... faster_rcnn_net_test_GPU"
	@echo "... ict_ssd_test_GPU"
	@echo "... landmark_net_test_GPU"
	@echo "... ssd_shuffle_test_GPU"
	@echo "... ssd_test_GPU"
	@echo "... body_detect.o"
	@echo "... body_detect.i"
	@echo "... body_detect.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

